### ISSUE TITLE
Research into Downsampling techniques

### ISSUE THREAD

**Issue by JoshC98** [NickThorne123/db_bench#11]
Conduct research in downsampling techniques and what ways would be the most efficient and work with larger datasets.

**Comment by NickThorne123** [comment]
LargestTriangleThreeBuckets is used in the example app [here](https://github.com/NickThorne123/db_bench/blob/c86a70bbe240d14e522c1d8af3be4be163f4c2fd/chdemoapp.py#L144)

Nice explainer video [here](https://clickhouse.com/videos/downsampling-time-series-data-with-plot-ly-and-ClickHouse)

**Comment by i-pitt** [comment]
[x] Downsampling definition
[x] LargestTriangleThreeBuckets and other technique definition and uses
[] How we will use this in our project

**Comment by JoshC98** [comment]
Looks good!
