### ISSUE TITLE
Ingest time series data for a single database (ClickhouseDB)

### ISSUE THREAD

**Issue by JoshC98** [NickThorne123/db_bench#13]
Import time series data for a single database (for example postgres) into the application and show it in a basic table in the web application.

**Comment by NickThorne123** [comment]
[This section](https://github.com/NickThorne123/db_bench/blob/c86a70bbe240d14e522c1d8af3be4be163f4c2fd/README.md?plain=1#L116) of the README.md has some SQL to autogenerate data.
