### ISSUE TITLE
Create Requirements document

### ISSUE THREAD

**Issue by i-pitt** [NickThorne123/db_bench#2]
Create a document detailing the requirements of the system and its scope.

- [x] Read the repo [README.md](https://github.com/NickThorne123/db_bench/blob/master/README.md).
- [x] Create SMART requirements Priority from Low (1) to High (3)
- [x] Make an Excel spreadsheet containing the SMART requirements and upload to wiki
- [x] Provide an overview and scope of the project

**Comment by i-pitt** [comment]
Moved the benchmarking and time series research to their own issue tickets.

**Comment by JoshC98** [comment]
Requirements reviewed - No issues, looks good.
