### ISSUE TITLE
Plotly Dash Training Course

### ISSUE THREAD

**Issue by NickThorne123** [NickThorne123/db_bench#43]
There's a nice 6 session YouTube course available for Plotly Dash

https://www.youtube.com/playlist?list=PLYD54mj9I2JevdabetHsJ3RLCeMyBNKYV

**Comment by DAghaSolent** [comment]
Closing this issue as we are utilising a different technology stack for our application which is Streamlit, this isn't a requirement anymore at this moment of time.
