### ISSUE TITLE
CI / CD Pipeline Setup

### ISSUE THREAD

**Issue by JoshC98** [NickThorne123/db_bench#5]
Be able to build a functional image after each request is pushed to the repo on branch.

Use Github Actions

**Comment by DAghaSolent** [comment]
@NickThorne123 Any recommendations for a decent platform that you might have played around with that we can utilise as a CICD pipeline for this project?

**Comment by NickThorne123** [comment]
Hi, Not directly (as you can see from the repo), but I have used pytest in VSCode, and am aware of GitHub CI/CD.

GitHub Actions for testing Python is described [here](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python)

And there's a good overview of testing [here](https://docs.github.com/en/actions/automating-builds-and-tests/about-continuous-integration)

I use Python Testing inside VSCode, as described [here](https://code.visualstudio.com/docs/python/testing), which could be added to this Flask/Dash app.
