### ISSUE TITLE
Research Time Series Databases

### ISSUE THREAD

**Issue by JoshC98** [NickThorne123/db_bench#7]
Get familiar with the various time series database offerings available (OSS and COTS). Look into 4 different time series databases.

**Comment by NickThorne123** [comment]
The ones I know of... 
[TimeScaleDB](https://www.timescale.com/)

[MongoDB TimeSeries collections](https://www.mongodb.com/docs/manual/core/timeseries-collections/)

[InfluxDB](https://www.influxdata.com/) <-- pretty sure this isn't SQL compliant ?

[Apache Druid](https://medium.com/subex-ai-labs/apache-druid-analytics-db-for-timeseries-data-a143856b5fa0) is one of the analytics tools which I ignored in favour of Dash. I guess there are some Apache time series DB offerings. Though I've found their products are more geared towards large engineering teams, and are not very quick to setup and use.

I guess DataDog and SnowFlake are the big commercial ones ?

**Comment by NickThorne123** [comment]
Interesting LinkedIn article[ 'Typers of Databases'](https://www.linkedin.com/posts/brijpandeyji_understanding-database-options-is-key-for-activity-7160957890193707009-Qiq2/)

Looks a bit light on proof points...


![Image](https://github.com/NickThorne123/db_bench/assets/18194218/10085c96-6dae-44fe-81da-9112d56f1e5a)

**Comment by i-pitt** [comment]
- [x] Types of databases
- [x] Time series definition
- [x] OSS/COTS definition and uses
- [x] How we plan to use this in our project

**Comment by i-pitt** [comment]
@lwoodRemote Could you tick off and add relevant tickboxes to the comment above for what your research covered?
