### ISSUE TITLE
Create Standards document

### ISSUE THREAD

**Issue by i-pitt** [NickThorne123/db_bench#9]
- [x] Branch naming Convention
- [x] Joel Test
- [x] Coding Convention
- [x] Documentation Standards

**Comment by kyleroberts27** [comment]
[] Branch naming Convention
[] Joel's

**Comment by NickThorne123** [comment]
I'm currently using this for eg ticket 123
nt_123_description

Or with 
feature/nt_123_description
bug/nt_123_description
